version: '3'
services:
  web:
    image: my_image
    container_name: test_container
    build:
      # . is the current directory. (or set the specific folder path)
      context: .
      # The docker file name
      dockerfile: Dockerfile