version: '3'
services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true # update automatically on windows OS
    build: 
      context: . # current project
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests: #Second service use for running test
    build: 
      context: . # current project
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] # Override container command
